"""__NAME__: public page + credit metering + Stripe Checkout, hosted on Modal.

Generated by the go-to-market skill. The product-specific part lives in
product.py (estimate_cost + run); this file is the storefront and should
rarely need editing.

Money model: prepaid credit packs, no subscription, no webhook.
  /api/checkout -> Stripe-hosted page -> redirect back with ?paid=<session_id>
  -> /api/claim retrieves the session, checks it is paid and tagged with this
  product, credits client_reference_id exactly once (claims dict).
A restricted key with only Checkout Sessions read+write is enough.

Accounts are a random access key held by the browser. The checkout session id
on the Stripe receipt restores the key, so there is no login to build.
"""
import hashlib
import os
import secrets
import time
from pathlib import Path

import modal

import product

SLUG = "__SLUG__"
HERE = Path(__file__).parent

image = (
    # debian_slim on this workspace's builder is bullseye and its apt mirror
    # 404s; an explicit bookworm base avoids that.
    modal.Image.from_registry("python:3.11-slim-bookworm")
    .run_commands("apt-get update && apt-get install -y ffmpeg")
    .pip_install("fastapi[standard]==0.115.6", "httpx==0.28.1", "python-multipart==0.0.20",
                 *product.PIP)
    .add_local_dir(HERE / "static", "/static")
    .add_local_python_source("product", *getattr(product, "MODULES", []))
)
if (HERE / "assets").exists():
    image = image.add_local_dir(HERE / "assets", "/assets")

app = modal.App(f"{SLUG}-web", image=image)
accounts = modal.Dict.from_name(f"{SLUG}-accounts", create_if_missing=True)
claims = modal.Dict.from_name(f"{SLUG}-claims", create_if_missing=True)
ipday = modal.Dict.from_name(f"{SLUG}-ipday", create_if_missing=True)
events = modal.Dict.from_name(f"{SLUG}-events", create_if_missing=True)

FREE_CREDITS = product.FREE_CREDITS
# Phones on a carrier share one public IP (CGNAT). A cap of 3 handed real
# visitors zero free credits; 20 still stops a script farming free keys.
IP_DAILY_FREE_KEYS = 20
PACKS = product.PACKS


def log(kind, **kw):
    events[f"{time.time():.6f}-{secrets.token_hex(3)}"] = {"kind": kind, "t": time.time(), **kw}


@app.function(secrets=[modal.Secret.from_name(f"{SLUG}-stripe"),
                       *[modal.Secret.from_name(n) for n in getattr(product, "SECRETS", [])]],
              scaledown_window=300, timeout=900)
@modal.concurrent(max_inputs=20)
@modal.asgi_app()
def web():
    import httpx
    from fastapi import FastAPI, HTTPException, Request
    from fastapi.responses import FileResponse, HTMLResponse, Response

    api = FastAPI(docs_url=None, redoc_url=None)
    stripe_key = os.environ["STRIPE_SECRET_KEY"]

    def ip_hash(req: Request) -> str:
        ip = (req.headers.get("x-forwarded-for") or req.client.host or "").split(",")[0].strip()
        return hashlib.sha256((ip + time.strftime("%Y-%m-%d")).encode()).hexdigest()[:24]

    def account(key: str) -> dict:
        if not key or len(key) != 32 or not key.isalnum():
            raise HTTPException(400, "missing or malformed access key")
        a = accounts.get(key)
        if a is None:
            raise HTTPException(404, "unknown access key")
        return a

    async def stripe(method: str, path: str, data=None) -> dict:
        async with httpx.AsyncClient(timeout=20) as c:
            r = await c.request(method, f"https://api.stripe.com/v1/{path}",
                                auth=(stripe_key, ""), data=data)
        body = r.json()
        if r.status_code >= 400:
            log("stripe_error", path=path.split("/")[0],
                msg=body.get("error", {}).get("message", "")[:200])
            raise HTTPException(502, "payment provider error, nothing was charged")
        return body

    @api.get("/", response_class=HTMLResponse)
    def index():
        return Path("/static/index.html").read_text()

    @api.get("/terms", response_class=HTMLResponse)
    def terms():
        return Path("/static/terms.html").read_text()

    @api.get("/static/{name}")
    def static(name: str):
        p = Path("/static") / Path(name).name
        if not p.is_file():
            raise HTTPException(404)
        return FileResponse(p)

    @api.get("/api/config")
    def config():
        return {"unit": product.UNIT, "free": FREE_CREDITS,
                "packs": {k: {"cents": v["cents"], "credits": v["credits"], "label": v["label"]}
                          for k, v in PACKS.items()},
                **getattr(product, "PUBLIC_CONFIG", {})}

    @api.post("/api/key")
    def new_key(req: Request):
        h = ip_hash(req)
        n = ipday.get(h, 0)
        ipday[h] = n + 1
        free = FREE_CREDITS if n < IP_DAILY_FREE_KEYS else 0
        key = secrets.token_hex(16)
        accounts[key] = {"credits": free, "paid": 0, "used": 0, "created": time.time()}
        log("key", free=free)
        return {"key": key, "credits": free}

    @api.get("/api/balance")
    def balance(key: str):
        a = account(key)
        return {"credits": a["credits"], "used": a["used"]}

    @api.post("/api/warm")
    async def warm():
        if hasattr(product, "warm"):
            await product.warm()
        return {"ok": True}

    @api.post("/api/run")
    async def run(req: Request):
        form = await req.form()
        key = str(form.get("key", ""))
        a = account(key)
        cost = await product.estimate_cost(form)          # may raise HTTPException(400)
        if a["credits"] < cost:
            raise HTTPException(402, f"this needs {cost} {product.UNIT} and you have {a['credits']}")
        # Debit before the work and refund on failure: two tabs cannot spend
        # the same credits, and a failed run never costs the customer.
        a["credits"] -= cost
        a["used"] += cost
        accounts[key] = a
        t0 = time.time()
        try:
            body, media_type = await product.run(form)
        except HTTPException:
            a = accounts.get(key); a["credits"] += cost; a["used"] -= cost; accounts[key] = a
            raise
        except Exception as e:
            a = accounts.get(key); a["credits"] += cost; a["used"] -= cost; accounts[key] = a
            log("run_error", err=type(e).__name__, msg=str(e)[:200])
            raise HTTPException(500, f"that failed; your {product.UNIT} were refunded")
        log("run", cost=cost, paid=a.get("paid", 0) > 0, secs=round(time.time() - t0, 1))
        return Response(body, media_type=media_type,
                        headers={"X-Credits-Left": str(a["credits"]), "X-Charged": str(cost)})

    @api.post("/api/checkout")
    async def checkout(req: Request):
        body = await req.json()
        key, pack = body.get("key", ""), body.get("pack", "")
        account(key)
        if pack not in PACKS:
            raise HTTPException(400, "unknown pack")
        p = PACKS[pack]
        base = f"https://{req.headers.get('host')}"
        s = await stripe("POST", "checkout/sessions", {
            "mode": "payment",
            "line_items[0][quantity]": "1",
            "line_items[0][price_data][currency]": "usd",
            "line_items[0][price_data][unit_amount]": str(p["cents"]),
            "line_items[0][price_data][product_data][name]": f"{product.NAME}: {p['label']}",
            "line_items[0][price_data][product_data][description]":
                f"Prepaid {product.UNIT}. They never expire.",
            "client_reference_id": key,
            "metadata[pack]": pack,
            "metadata[product]": SLUG,
            "success_url": f"{base}/?paid={{CHECKOUT_SESSION_ID}}",
            "cancel_url": f"{base}/#pricing",
            "allow_promotion_codes": "true",
        })
        log("checkout", pack=pack)
        return {"url": s["url"]}

    @api.get("/api/claim")
    async def claim(session_id: str):
        if not session_id.startswith("cs_") or len(session_id) > 200:
            raise HTTPException(400, "not a checkout session")
        try:
            s = await stripe("GET", f"checkout/sessions/{session_id}")
        except HTTPException:
            raise HTTPException(404, "could not find that purchase")
        meta = s.get("metadata") or {}
        if meta.get("product") != SLUG:            # one Stripe account, many products
            raise HTTPException(404, f"not a {product.NAME} purchase")
        if s.get("payment_status") != "paid":
            raise HTTPException(402, "that payment has not completed")
        owner = s["client_reference_id"]
        if claims.get(session_id) is None:
            p = PACKS[meta["pack"]]
            a = accounts.get(owner) or {"credits": 0, "paid": 0, "used": 0, "created": time.time()}
            a["credits"] += p["credits"]
            a["paid"] = a.get("paid", 0) + p["credits"]
            accounts[owner] = a
            claims[session_id] = {"key": owner, "t": time.time()}
            log("paid", pack=meta["pack"], cents=s.get("amount_total"))
        return {"key": owner, "credits": accounts.get(owner)["credits"]}

    @api.post("/api/feedback")
    async def feedback(req: Request):
        body = await req.json()
        msg = str(body.get("message", ""))[:2000].strip()
        if msg:
            log("feedback", message=msg, contact=str(body.get("contact", ""))[:200])
        return {"ok": True}

    return api
